const FBTI_DATA = (() => {
  const dimensions = [
    {
      key: "C",
      name: "竞技伦理",
      left: "规则坚守",
      right: "荣誉至上",
      leftShort: "守规",
      rightShort: "争冠",
      description: "你更相信比赛的秩序，还是更相信奖杯会定义一切。",
    },
    {
      key: "T",
      name: "团队倾向",
      left: "团队至上",
      right: "个人英雄",
      leftShort: "团队",
      rightShort: "巨星",
      description: "你更吃团队流转，还是更吃一个人把天聊死的瞬间。",
    },
    {
      key: "R",
      name: "风险偏好",
      left: "保守求稳",
      right: "冒险激进",
      leftShort: "稳健",
      rightShort: "激进",
      description: "你更偏向控住局面，还是愿意把胜负推上高杠杆。",
    },
    {
      key: "E",
      name: "情绪特质",
      left: "冷静隐忍",
      right: "张扬外放",
      leftShort: "隐忍",
      rightShort: "外放",
      description: "你更像把情绪吞回去的人，还是让全场都知道你在燃烧的人。",
    },
  ];

  const introQuestions = {
    gate: {
      id: "gate",
      group: "开场分流",
      text: "当你的球迷朋友得知你准备成为一名球迷，你被问到的第一个问题往往不是“你支持哪支球队？”，而是：",
      emphasis: "梅西还是C罗？",
      options: [
        { code: "A", value: "both", label: "很难选择，都是球王" },
        { code: "B", value: "messi", label: "梅西" },
        { code: "C", value: "ronaldo", label: "C罗" },
        { code: "D", value: "unknown", label: "我都不是很了解" },
        { code: "E", value: "meme", label: "两个乐子" },
      ],
    },
    messiDepth: {
      id: "messiDepth",
      group: "成分校准",
      text: "你爱梅西有多深？",
      options: [
        { code: "A", value: "respectBoth", label: "其实C罗也很好，非要选一个的话就是梅西了" },
        { code: "B", value: "light", label: "我平时不怎么看球，只是对梅西更有好感" },
        { code: "C", value: "normal", label: "我只是更喜欢梅西，但从来不踩C罗" },
        { code: "D", value: "goat", label: "梅西是真正的GOAT，当代唯一真球王" },
        { code: "E", value: "extreme", label: "我是纯正阿萨塔，C罗纯纯跳水王子、沙漠骆驼" },
      ],
    },
    ronaldoDepth: {
      id: "ronaldoDepth",
      group: "成分校准",
      text: "你爱C罗有多深？",
      options: [
        { code: "A", value: "respectBoth", label: "其实梅西也很好，非要选一个的话就是C罗了" },
        { code: "B", value: "light", label: "我平时不怎么看球，只是对C罗更有好感" },
        { code: "C", value: "normal", label: "我只是更喜欢C罗，但从来不踩梅西" },
        { code: "D", value: "goat", label: "C罗是真正的GOAT，当代唯一真球王" },
        { code: "E", value: "extreme", label: "我是纯正罗结晶，梅西纯纯点球杯冠军、每周杯冠军" },
      ],
    },
    memeDepth: {
      id: "memeDepth",
      group: "互联网耐受度",
      text: "看来你有点独到的见解。那么对于互联网上旷日持久的梅罗之争，你是怎样看待的？",
      options: [
        { code: "A", value: "none", label: "不感兴趣" },
        { code: "B", value: "watch", label: "可以当个乐子看看" },
        { code: "C", value: "debateOnly", label: "对足球的全部了解都来自梅罗粉丝的辩论" },
        { code: "D", value: "troll", label: "我不仅爱看乐子，更爱当串子" },
        { code: "E", value: "sofa", label: "躺在床上看，坐在沙发上看" },
      ],
    },
    trollSide: {
      id: "trollSide",
      group: "隐藏分支",
      text: "你通常更喜欢反串哪一边？",
      options: [
        { code: "A", value: "fakeMessi", label: "串阿萨塔" },
        { code: "B", value: "fakeRonaldo", label: "串罗结晶" },
        { code: "C", value: "both", label: "两边都串，然后坐山观虎斗" },
        { code: "D", value: "joke", label: "开玩笑的，其实没什么可串的" },
        { code: "E", value: "skewer", label: "肉串？" },
      ],
    },
  };

  const hiddenQuestion = {
    id: "offPitchLife",
    group: "隐藏款问题",
    text: "如果突然有人说：别聊球了，下面哪个更适合你？",
    options: [
      { code: "A", value: "play", label: "踢球" },
      { code: "B", value: "watch", label: "看球" },
      { code: "C", value: "neither", label: "不踢球也不看球" },
      { code: "D", value: "game", label: "还是游戏更适合我" },
      { code: "E", value: "cat", label: "还是猫猫更适合我" },
    ],
  };

  const hiddenConfirmationQuestions = {
    game: {
      id: "gameAffinity",
      text: "认真说，你对游戏的痴迷程度更接近哪一种？",
      options: [
        { code: "A", value: "A", label: "偶尔玩玩，想起来才打开" },
        { code: "B", value: "B", label: "有空会玩，但不会影响其他安排" },
        { code: "C", value: "C", label: "算是稳定爱好，和足球差不多" },
        { code: "D", value: "D", label: "一有时间就想开一局，已经很难割舍" },
        { code: "E", value: "E", label: "游戏就是主场，其他事情都得往后排" },
      ],
    },
    cat: {
      id: "catAffinity",
      text: "认真说，你对猫猫的痴迷程度更接近哪一种？",
      options: [
        { code: "A", value: "A", label: "路过会看一眼，仅此而已" },
        { code: "B", value: "B", label: "觉得可爱，但不会特意寻找" },
        { code: "C", value: "C", label: "经常看猫猫内容，算是稳定爱好" },
        { code: "D", value: "D", label: "见到猫就走不动路，手机里全是猫" },
        { code: "E", value: "E", label: "猫猫拥有最高优先级，其他事情都可以等等" },
      ],
    },
  };

  const answerModeQuestion = {
    id: "answerMode",
    text: "你已经做了几道题了，这个阅读量对你来说是否太大？",
    options: [
      {
        code: "A",
        value: "precise",
        label: "阅读量不大，继续做5个选项的精准测试",
      },
      {
        code: "B",
        value: "quick",
        label: "懒得看这么多字，后面的题做3个选项的粗略测试",
      },
      {
        code: "C",
        value: "random",
        label: "算了我不想做了，随便给我个人格得了",
      },
    ],
  };

  const fanQuestions = [
    {
      id: "fan_c1",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "补时阶段，对方禁区里一个疑似手球没有吹，你的第一反应是：",
      options: [
        "裁判没吹就继续踢，赢也要赢得站得住",
        "有争议先尊重判罚，别把比赛变成吵架",
        "看VAR怎么说，我先不急着站队",
        "淘汰赛哪有那么干净，能赢就先赢",
        "冠军路上不问过程，史书只记得捧杯的人",
      ],
    },
    {
      id: "fan_t1",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "一场硬仗里，你最容易被哪种画面打动？",
      options: [
        "十几脚传递把对手整条防线拆开",
        "队友不断补位、协防、互相擦屁股",
        "都行，精彩就好",
        "巨星突然一个爆点改写比赛",
        "一个人扛着球队往前走，这才叫主角",
      ],
    },
    {
      id: "fan_r1",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "领先一球进入最后十分钟，你希望球队怎么踢？",
      options: [
        "收住阵型，能把球控在脚下就别冒险",
        "先稳住，反击机会好再打",
        "看场面，别固定一套",
        "继续压迫，别给对手喘气",
        "趁他病要他命，第二球才是最好的防守",
      ],
    },
    {
      id: "fan_e1",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "主队被绝平后，你更像哪一种状态？",
      options: [
        "沉默十分钟，等情绪过去再说话",
        "先深呼吸，别把火撒给身边人",
        "看比赛重要程度",
        "忍不住立刻开麦复盘裁判和防线",
        "直接从沙发上弹起来，整栋楼都知道我破防了",
      ],
    },
    {
      id: "fan_c2",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "球队有机会用一次战术犯规打断对方单刀，你会怎么评价？",
      options: [
        "该犯就犯，这叫职业",
        "可以接受，规则允许范围内就是博弈",
        "看动作大小和比赛阶段",
        "心里会有点别扭",
        "宁可输，也不想靠这种方式苟住",
      ],
    },
    {
      id: "fan_t2",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "如果一支球队战术很完整，但缺少能一锤定音的人，你会觉得：",
      options: [
        "上限不够，关键时刻就得有人不讲理",
        "体系再好也需要最后那把刀",
        "看对手和赛程",
        "完整体系本身就能制造答案",
        "团队能托住所有人，才是真的强",
      ],
    },
    {
      id: "fan_r2",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "点球大战前第五个主罚该让谁上？",
      options: [
        "状态最热、心脏最大的人，哪怕他不是常规点球手",
        "敢站出来的人就值得信",
        "听教练安排",
        "平时训练命中率最高的人",
        "固定点球手，别临场整活",
      ],
    },
    {
      id: "fan_e2",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "你的偶像进球后做了一个很夸张的庆祝动作，你会：",
      options: [
        "爽，这种气场就是要放出来",
        "只要不是侮辱对手，张扬一点没问题",
        "看动作好不好看",
        "能低调点更好，别给自己招黑",
        "进球归进球，情绪还是收一点比较体面",
      ],
    },
    {
      id: "fan_c3",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "喜欢的球员被骂“太老实，不够狠”，你更想回一句：",
      options: [
        "这叫球品，不是缺点",
        "老实人也能成为传奇",
        "看他在什么位置、什么任务",
        "顶级赛场确实需要一点锋芒",
        "不够狠就别谈最高荣誉",
      ],
    },
    {
      id: "fan_t3",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "你更愿意把一支球队的功劳归给谁？",
      options: [
        "整体结构，所有人都在正确位置上",
        "教练和团队搭好了地基",
        "几方面都有",
        "核心球星，他把普通回合变成决定性回合",
        "没有头牌就没有故事，英雄才是入口",
      ],
    },
    {
      id: "fan_r3",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "面对强队，你支持弱队怎么踢？",
      options: [
        "先摆住，活到最后才有机会",
        "降低失误，等对方自己急",
        "看双方状态",
        "主动抢开局，先把气势打出来",
        "搏命高压，输了也要让对面出汗",
      ],
    },
    {
      id: "fan_e3",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "被朋友说你看球太上头时，你更接近：",
      options: [
        "我其实上头也不太表现出来",
        "我会努力保持正常人类状态",
        "看比赛重要性",
        "足球不就是用来上头的吗",
        "不上头看什么球，我负责把气氛顶满",
      ],
    },
    {
      id: "fan_c4",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "偶像决赛赢了，但赛后全网都在说靠争议点球，你会：",
      options: [
        "赢了就是赢了，冠军会自己说话",
        "争议也是比赛的一部分",
        "先看完整回放再判断",
        "这个冠军多少会被打折",
        "我会很难心安，宁愿赢得更干净",
      ],
    },
    {
      id: "fan_t4",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "如果只能保留一种资产，你选：",
      options: [
        "一个随时能爆破防线的超级边锋",
        "一个决定比赛气质的头牌",
        "看球队缺什么",
        "一套稳定的中后场体系",
        "一群愿意互相跑到死的队友",
      ],
    },
    {
      id: "fan_r4",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "你看到门将第85分钟还在后场玩短传，会怎么想？",
      options: [
        "好看，胆子大才有上限",
        "现代足球就得有这种勇气",
        "别失误就行",
        "差不多得了，领先时别玩火",
        "赶紧大脚解围，我的心脏不是公共用品",
      ],
    },
    {
      id: "fan_e4",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "球队赢下德比，你发朋友圈的风格更像：",
      options: [
        "九宫格加大字报，今晚谁也别睡",
        "发梗图，顺手点名几个老朋友",
        "看心情",
        "发一条简短比分就够了",
        "不发，赢球的快乐自己消化",
      ],
    },
  ];

  const noviceQuestions = [
    {
      id: "novice_c1",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "玩一场重要游戏时，如果大家发现一个灰色技巧能提高胜率，你会：",
      options: [
        "不用，赢也要赢得舒服",
        "先确认这算不算违规",
        "大家怎么定我就怎么来",
        "只要没明令禁止，就可以试试",
        "赢面最大的方法就该用",
      ],
    },
    {
      id: "novice_t1",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "团队项目里，你最欣赏哪种人？",
      options: [
        "能把每个人都串起来的人",
        "默默补位、让整体顺的人",
        "都可以，看具体情况",
        "关键时刻敢站出来的人",
        "一个人直接把结果改写的人",
      ],
    },
    {
      id: "novice_r1",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "事情快成功但还没结束时，你更倾向：",
      options: [
        "先稳住，别最后翻车",
        "少犯错就是最优解",
        "看剩下多少时间",
        "继续加码，把优势扩大",
        "机会来了就要一波带走",
      ],
    },
    {
      id: "novice_e1",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "计划突然被打乱时，你通常会：",
      options: [
        "先安静下来，重新排顺序",
        "忍住脾气，先处理问题",
        "看打乱到什么程度",
        "会明显烦躁，但还能干活",
        "情绪会直接写在脸上",
      ],
    },
    {
      id: "novice_c2",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "如果一次小小的钻空子不会被发现，你会怎么想？",
      options: [
        "有用就行，现实本来如此",
        "偶尔灵活一点没什么",
        "看代价和场合",
        "心里会有点不踏实",
        "不想这么赢，没意思",
      ],
    },
    {
      id: "novice_t2",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "你更喜欢哪种故事？",
      options: [
        "主角在最后一刻逆天改命",
        "天才人物把不可能变成可能",
        "都能看",
        "一群人互相成就",
        "团队一步步把大事做成",
      ],
    },
    {
      id: "novice_r2",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "面对一个回报很高但失败率也高的选择，你更可能：",
      options: [
        "冲，人生需要这种节点",
        "可以试，别太保守",
        "算完再说",
        "除非准备充分，否则不动",
        "不碰，稳稳拿到已有收益",
      ],
    },
    {
      id: "novice_e2",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "特别开心的时候，你更像：",
      options: [
        "马上分享，让所有人一起热闹",
        "会明显表现出来",
        "看身边是谁",
        "开心但不一定张扬",
        "心里很爽，表面很淡定",
      ],
    },
    {
      id: "novice_c3",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "如果朋友说你太讲原则，你会：",
      options: [
        "原则感不是坏事",
        "至少我知道底线在哪",
        "也许吧，看什么事",
        "有时候确实该现实一点",
        "规则只是工具，目标才重要",
      ],
    },
    {
      id: "novice_t3",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "做小组任务时，最让你安心的是：",
      options: [
        "每个人都知道自己该做什么",
        "有人愿意互相兜底",
        "能完成就行",
        "有一个强人能拍板",
        "有个大腿负责把结果拉满",
      ],
    },
    {
      id: "novice_r3",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "你更喜欢哪种路线？",
      options: [
        "慢一点，但成功率高",
        "稳扎稳打，少出意外",
        "两种都能接受",
        "快一点，承担一些波动",
        "高风险高回报才有意思",
      ],
    },
    {
      id: "novice_e3",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "被误解时，你通常更像：",
      options: [
        "先憋着，等合适时候解释",
        "会忍一忍，不想把场面搞大",
        "看误解有多严重",
        "会马上表达不满",
        "必须当场说清楚，气势不能输",
      ],
    },
    {
      id: "novice_c4",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "如果一个结果很漂亮，但过程不太体面，你会：",
      options: [
        "结果漂亮就足够了",
        "过程有瑕疵也可以接受",
        "看瑕疵有多大",
        "会影响我对结果的评价",
        "过程不体面，结果也很难真正漂亮",
      ],
    },
    {
      id: "novice_t4",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "你更愿意成为哪种人？",
      options: [
        "所有人都等我解决问题的关键人物",
        "能在关键时刻一锤定音的人",
        "都可以",
        "让团队运转更顺的人",
        "大家离不开的稳定连接点",
      ],
    },
    {
      id: "novice_r4",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "临场出现一个大胆新方案，你会：",
      options: [
        "试，现场机会往往只出现一次",
        "如果直觉不错就上",
        "先听两边理由",
        "没有准备就别乱动",
        "关键时候别实验，按原计划来",
      ],
    },
    {
      id: "novice_e4",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "朋友聚会里，你更常处于：",
      options: [
        "气氛组，负责把场子点起来",
        "话很多，情绪来得快",
        "看熟不熟",
        "比较克制，熟了才打开",
        "安静观察，能不抢戏就不抢戏",
      ],
    },
  ];

  const results = [
    { key: "规则坚守×团队至上", label: "隐身者", player: "梅西", extreme: "梅西 隐身梅" },
    { key: "规则坚守×个人英雄", label: "绅士", player: "莫德里奇" },
    { key: "荣誉至上×团队至上", label: "红牌英雄", player: "巴尔韦德" },
    { key: "荣誉至上×个人英雄", label: "独裁者", player: "姆巴佩", extreme: "c罗 数据罗" },
    { key: "规则坚守×保守求稳", label: "老实人", player: "坎特", extreme: "梅西 隐身梅" },
    { key: "规则坚守×冒险激进", label: "骑士", player: "贝林厄姆" },
    { key: "荣誉至上×保守求稳", label: "卧草者", player: "大马丁" },
    { key: "荣誉至上×冒险激进", label: "跳水者", player: "C罗", extreme: "c罗 跳水罗" },
    { key: "规则坚守×冷静隐忍", label: "小鹿斑比", player: "穆西亚拉", extreme: "梅西 受气梅" },
    { key: "规则坚守×张扬外放", label: "魔人布欧", player: "哈兰德" },
    { key: "荣誉至上×冷静隐忍", label: "黄牌大师", player: "卡塞米罗" },
    { key: "荣誉至上×张扬外放", label: "挑衅者", player: "维尼修斯", extreme: "c罗 詹姆斯" },
    { key: "团队至上×保守求稳", label: "回传者", player: "赖斯", extreme: "梅西 詹姆斯" },
    { key: "团队至上×冒险激进", label: "抽奖者", player: "维尔茨" },
    { key: "个人英雄×保守求稳", label: "吃饼者", player: "哈兰德" },
    { key: "个人英雄×冒险激进", label: "舞者", player: "内马尔", extreme: "c罗 浪射罗" },
    { key: "团队至上×冷静隐忍", label: "“我的”人", player: "哈利凯恩", extreme: "梅西 散步梅" },
    { key: "团队至上×张扬外放", label: "保镖", player: "德保罗" },
    { key: "个人英雄×冷静隐忍", label: "亚洲式球王", player: "孙兴慜" },
    { key: "个人英雄×张扬外放", label: "皇毛", player: "亚马尔", extreme: "c罗 摊手罗" },
    { key: "保守求稳×冷静隐忍", label: "苟分者", player: "罗德里", extreme: "梅西 散步梅" },
    { key: "保守求稳×张扬外放", label: "场上教练", player: "基米希" },
    { key: "冒险激进×冷静隐忍", label: "带派者", player: "奥利赛" },
    { key: "冒险激进×张扬外放", label: "摊手者", player: "B费", extreme: "c罗 越位罗" },
  ];

  const hiddenResults = {
    game: {
      label: "游戏王",
      player: "登贝莱",
      kind: "隐藏人格",
      reason: "你不仅选择了游戏，还在二次确认中表现出极高痴迷度，系统正式把你送进游戏分支。",
    },
    cat: {
      label: "哈基米",
      player: "阿什拉夫",
      kind: "隐藏人格",
      reason: "你不仅选择了猫猫，还在二次确认中表现出极高痴迷度，系统判定你的精神边后卫已经转入猫科。",
    },
    troll: {
      label: "串子",
      player: "",
      kind: "隐藏人格",
      reason: "你在开场分流里主动暴露反串倾向，正常人格库只能先退后一步。",
    },
    fun: {
      label: "乐子人",
      player: "",
      kind: "隐藏人格",
      reason: "你对梅罗之争的投入主要来自围观与吃瓜，系统把你归入看台娱乐部门。",
    },
    balanced: {
      label: "勤笑公",
      player: "莱奥",
      kind: "隐藏人格",
      reason: "你的四个维度强度完全相同，系统判定你达成了罕见的全维度均衡。",
    },
  };

  return {
    dimensions,
    dimensionOrder: dimensions.map((dimension) => dimension.key),
    introQuestions,
    answerModeQuestion,
    hiddenQuestion,
    hiddenConfirmationQuestions,
    questionBanks: {
      fan: fanQuestions,
      novice: noviceQuestions,
    },
    results,
    hiddenResults,
  };
})();
