const FBTI_DATA = (() => {
  const dimensions = [
    {
      key: "C",
      name: "竞技伦理",
      left: "规则坚守",
      right: "荣誉至上",
      leftShort: "守规",
      rightShort: "争冠",
      description: "你更相信比赛的秩序，还是更相信奖杯会定义一切。",
    },
    {
      key: "T",
      name: "团队倾向",
      left: "团队至上",
      right: "个人英雄",
      leftShort: "团队",
      rightShort: "巨星",
      description: "你更吃团队流转，还是更吃一个人把天聊死的瞬间。",
    },
    {
      key: "R",
      name: "风险偏好",
      left: "保守求稳",
      right: "冒险激进",
      leftShort: "稳健",
      rightShort: "激进",
      description: "你更偏向控住局面，还是愿意把胜负推上高杠杆。",
    },
    {
      key: "E",
      name: "情绪特质",
      left: "冷静隐忍",
      right: "张扬外放",
      leftShort: "隐忍",
      rightShort: "外放",
      description: "你更像把情绪吞回去的人，还是让全场都知道你在燃烧的人。",
    },
  ];

  const introQuestions = {
    gate: {
      id: "gate",
      group: "开场分流",
      text: "当你的球迷朋友得知你准备成为一名球迷，你被问到的第一个问题往往不是“你支持哪支球队？”，而是：",
      emphasis: "梅西还是C罗？",
      options: [
        { code: "A", value: "both", label: "很难选择，都是球王" },
        { code: "B", value: "messi", label: "梅西" },
        { code: "C", value: "ronaldo", label: "C罗" },
        { code: "D", value: "unknown", label: "我都不是很了解" },
        { code: "E", value: "meme", label: "两个乐子" },
      ],
    },
    messiDepth: {
      id: "messiDepth",
      group: "成分校准",
      text: "你爱梅西有多深？",
      options: [
        { code: "A", value: "respectBoth", label: "其实C罗也很好，非要选一个的话就是梅西了" },
        { code: "B", value: "light", label: "我平时不怎么看球，只是对梅西更有好感" },
        { code: "C", value: "normal", label: "我只是更喜欢梅西，但从来不踩C罗" },
        { code: "D", value: "goat", label: "梅西是真正的GOAT，当代唯一真球王" },
        { code: "E", value: "extreme", label: "我是纯正阿萨塔，C罗纯纯跳水王子、沙漠骆驼" },
      ],
    },
    ronaldoDepth: {
      id: "ronaldoDepth",
      group: "成分校准",
      text: "你爱C罗有多深？",
      options: [
        { code: "A", value: "respectBoth", label: "其实梅西也很好，非要选一个的话就是C罗了" },
        { code: "B", value: "light", label: "我平时不怎么看球，只是对C罗更有好感" },
        { code: "C", value: "normal", label: "我只是更喜欢C罗，但从来不踩梅西" },
        { code: "D", value: "goat", label: "C罗是真正的GOAT，当代唯一真球王" },
        { code: "E", value: "extreme", label: "我是纯正罗结晶，梅西纯纯点球杯冠军、每周杯冠军" },
      ],
    },
    memeDepth: {
      id: "memeDepth",
      group: "互联网耐受度",
      text: "看来你有点独到的见解。那么对于互联网上旷日持久的梅罗之争，你是怎样看待的？",
      options: [
        { code: "A", value: "none", label: "不感兴趣" },
        { code: "B", value: "watch", label: "可以当个乐子看看" },
        { code: "C", value: "debateOnly", label: "对足球的全部了解都来自梅罗粉丝的辩论" },
        { code: "D", value: "troll", label: "我不仅爱看乐子，更爱当串子" },
        { code: "E", value: "sofa", label: "躺在床上看，坐在沙发上看" },
      ],
    },
    trollSide: {
      id: "trollSide",
      group: "隐藏分支",
      text: "你通常更喜欢反串哪一边？",
      options: [
        { code: "A", value: "fakeMessi", label: "串阿萨塔" },
        { code: "B", value: "fakeRonaldo", label: "串罗结晶" },
        { code: "C", value: "both", label: "两边都串，然后坐山观虎斗" },
        { code: "D", value: "joke", label: "开玩笑的，其实没什么可串的" },
        { code: "E", value: "skewer", label: "肉串？" },
      ],
    },
  };

  const hiddenQuestion = {
    id: "offPitchLife",
    group: "隐藏款问题",
    text: "如果突然有人说：别聊球了，下面哪个更适合你？",
    options: [
      { code: "A", value: "play", label: "踢球" },
      { code: "B", value: "watch", label: "看球" },
      { code: "C", value: "neither", label: "不踢球也不看球" },
      { code: "D", value: "game", label: "还是游戏更适合我" },
      { code: "E", value: "cat", label: "还是猫猫更适合我" },
    ],
  };

  const hiddenConfirmationQuestions = {
    game: {
      id: "gameAffinity",
      text: "认真说，你对游戏的痴迷程度更接近哪一种？",
      options: [
        { code: "A", value: "A", label: "偶尔玩玩，想起来才打开" },
        { code: "B", value: "B", label: "有空会玩，但不会影响其他安排" },
        { code: "C", value: "C", label: "算是稳定爱好，和足球差不多" },
        { code: "D", value: "D", label: "一有时间就想开一局，已经很难割舍" },
        { code: "E", value: "E", label: "游戏就是主场，其他事情都得往后排" },
      ],
    },
    cat: {
      id: "catAffinity",
      text: "认真说，你对猫猫的痴迷程度更接近哪一种？",
      options: [
        { code: "A", value: "A", label: "路过会看一眼，仅此而已" },
        { code: "B", value: "B", label: "觉得可爱，但不会特意寻找" },
        { code: "C", value: "C", label: "经常看猫猫内容，算是稳定爱好" },
        { code: "D", value: "D", label: "见到猫就走不动路，手机里全是猫" },
        { code: "E", value: "E", label: "猫猫拥有最高优先级，其他事情都可以等等" },
      ],
    },
  };

  const answerModeQuestion = {
    id: "answerMode",
    text: "你已经做了几道题了，这个阅读量对你来说是否太大？",
    options: [
      {
        code: "A",
        value: "precise",
        label: "阅读量不大，继续做5个选项的精准测试",
      },
      {
        code: "B",
        value: "quick",
        label: "懒得看这么多字，后面的题做3个选项的粗略测试",
      },
      {
        code: "C",
        value: "random",
        label: "算了我不想做了，随便给我个人格得了",
      },
    ],
  };

  const fanQuestions = [
    {
      id: "fan_c1",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "主队补时绝杀，但进球前有一个明显疑似手球，裁判没有回看。你的第一反应是：",
      options: [
        "必须回看，哪怕绝杀被吹掉也要赢得干净",
        "希望流程走完整，别让胜利背着明显争议",
        "先等官方判定，我不急着站队",
        "裁判认了就先认，争议以后再讨论",
        "绝杀就是绝杀，冠军路上不可能每一步都完美",
      ],
    },
    {
      id: "fan_t1",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "一场强强对话里，哪种进球最能让你服气？",
      options: [
        "全队连续跑位传切，把对手整条防线拆开",
        "多人配合制造空当，最后一脚只是水到渠成",
        "都行，精彩就好",
        "核心球星突然爆点，把僵局打穿",
        "一个人从无到有解决比赛，这才叫巨星",
      ],
    },
    {
      id: "fan_r1",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "领先一球进入最后十分钟，你最希望球队怎么处理节奏？",
      options: [
        "收住阵型控住球权，宁愿难看也绝不冒险",
        "先稳住，只有把握很大的反击才打",
        "看场面，别固定一套",
        "继续保持压迫，有好机会就争第二球",
        "继续压上狠狠干，第二球才是最好的防守",
      ],
    },
    {
      id: "fan_e1",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "主队最后时刻被绝平，你更像哪种状态？",
      options: [
        "安静关掉直播，先自己消化不打扰任何人",
        "会郁闷，但尽量不把情绪甩给别人",
        "看比赛重要程度",
        "立刻在群里吐槽几句，情绪得有出口",
        "直接破防开麦，裁判、后防、教练一个都跑不了",
      ],
    },
    {
      id: "fan_c2",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "淘汰赛最后阶段，对手即将形成单刀，你方后腰可以用一次拉人吃牌把球断掉。你会怎么评价？",
      options: [
        "必须拉，吃牌也值，淘汰赛先活下来",
        "可以犯规，但动作别冲着伤人去",
        "看动作大小和比赛阶段",
        "战术上能理解，但我会觉得不太体面",
        "宁可让他射门，也不想靠这种犯规保命",
      ],
    },
    {
      id: "fan_t2",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "一支球队体系很完整，但关键战总差一个能爆点的人。你会觉得：",
      options: [
        "没有顶级巨星兜底，再完整的体系也难拿最高荣誉",
        "体系再好，也需要一个核心来决定上限",
        "看对手和赛程",
        "完整体系可以弥补一部分爆点不足",
        "真正强队靠整体制造答案，不该等救世主",
      ],
    },
    {
      id: "fan_r2",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "点球大战第五罚，常规点球手状态一般，替补席上有人刚上场但气势很足。你倾向：",
      options: [
        "就让气势最足的人上，赌的就是大心脏",
        "可以换状态更好的人，别太死守名单",
        "听教练安排",
        "优先平时命中率和既定顺序",
        "固定点球手上，生死时刻别拿命运试手感",
      ],
    },
    {
      id: "fan_e2",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "你的偶像在客场绝杀后，对着看台做了一个很张扬的庆祝动作。你会：",
      options: [
        "爽，客场就该这么点燃全场，让他们记住你",
        "只要不是侮辱对手，张扬一点没问题",
        "看动作好不好看",
        "能收一点更好，别把火药味拉太满",
        "进球后还挑情绪很掉价，真正强者不需要这样",
      ],
    },
    {
      id: "fan_c3",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "你喜欢的球员因为从不假摔、很少抱怨裁判，被骂“太老实，不会赢球”。你更想回：",
      options: [
        "能守住底线才是真高级，赢球不能靠脏招",
        "球品是加分项，但关键时刻也要更强硬",
        "看他在什么位置、什么任务",
        "顶级赛场确实需要一点合理施压",
        "太干净就别谈最高荣誉，冠军不是发道德奖",
      ],
    },
    {
      id: "fan_t3",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "一支球队夺冠后，你更愿意把最大功劳归给谁？",
      options: [
        "完整体系和每个角色的执行，没人能凌驾球队",
        "教练框架和队友支撑占很大一部分",
        "几方面都有",
        "核心球星，他把普通回合拔高成决定性回合",
        "头牌巨星，没有他就没有这座冠军的故事",
      ],
    },
    {
      id: "fan_r3",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "弱队面对明显更强的对手，你最支持哪种踢法？",
      options: [
        "极低位先守住，拖到点球或最后一击才有机会",
        "降低失误，等对方急起来再找机会",
        "看双方状态",
        "开局主动抢一段，先把气势打出来",
        "搏命高压狠狠干，输五个也不能缩着等死",
      ],
    },
    {
      id: "fan_e3",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "朋友说你看球太上头，你真实情况更接近：",
      options: [
        "我会把情绪压到赛后，现场几乎看不出来",
        "我会有情绪，但尽量不影响别人",
        "看比赛重要性",
        "会吐槽会发消息，足球本来就有情绪",
        "不上头看什么球，群聊和客厅都得被我点燃",
      ],
    },
    {
      id: "fan_c4",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "偶像决赛夺冠，但关键点球争议很大，赛后全网吵翻。你会：",
      options: [
        "冠军就是冠军，争议也是冠军叙事的一部分",
        "争议可以讨论，但奖杯不会因此贬值太多",
        "先看完整回放再判断",
        "会开心，但承认这个冠军多少有瑕疵",
        "如果真靠误判获利，我很难真心庆祝",
      ],
    },
    {
      id: "fan_t4",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "如果你支持的球队只能保留一种建队资产，你选：",
      options: [
        "一个能无视体系、单点爆破的超级巨星",
        "一个关键时刻必须优先拿球的头牌",
        "看球队缺什么",
        "一套能稳定托底的中后场体系",
        "一套全员执行、互相补位的完整球队机器",
      ],
    },
    {
      id: "fan_r4",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "第85分钟领先一球，门将还在禁区附近坚持短传组织。你会怎么想？",
      options: [
        "继续短传，顶级球队就该敢在刀尖上控制比赛",
        "有出球能力就可以坚持，别一慌就大脚",
        "别失误就行",
        "领先时别硬秀，必要时该大脚就大脚",
        "马上大脚解围，禁区前任何风险都不可接受",
      ],
    },
    {
      id: "fan_e4",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "球队赢下死敌德比，你发动态的风格更像：",
      options: [
        "九宫格加大字报，顺手点名老对手，今晚谁也别睡",
        "发梗图，顺手点名几个老朋友",
        "看心情",
        "发一条简短比分，表达一下就够了",
        "不发，赢球的快乐自己消化",
      ],
    },
  ];

  const noviceQuestions = [
    {
      id: "novice_c1",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "你和朋友组队打决赛，发现一个大家都知道但很有争议的“卡机制”打法能提高胜率。你会：",
      options: [
        "坚决不用，宁愿输也不靠这种争议打法夺冠",
        "先确认规则边界，不确定合规就不用",
        "大家怎么定我就怎么来",
        "如果赛方没禁，关键局用一下也能接受",
        "决赛就是要赢，规则没写死就该把优势用满",
      ],
    },
    {
      id: "novice_t1",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "一个小队要完成限时挑战，你最欣赏哪种表现？",
      options: [
        "所有人分工清楚、互相配合，把挑战稳稳做完",
        "有人愿意补位兜底，让整体节奏顺起来",
        "都可以，看具体情况",
        "关键时刻敢多承担一点的人",
        "一个人直接接管局面，把结果强行改写",
      ],
    },
    {
      id: "novice_r1",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "你们已经快拿到胜利，但还剩最后一小段不确定环节。你更倾向：",
      options: [
        "立刻收住，别再增加任何可能翻车的动作",
        "先稳住，只有很有把握的优化才做",
        "看剩下多少时间",
        "继续加码，把优势再扩大一点",
        "继续冲一波，能彻底杀死悬念就别保守",
      ],
    },
    {
      id: "novice_e1",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "一场你很在乎的活动突然出了意外，你通常会：",
      options: [
        "先完全冷静下来，几乎不让别人看出情绪",
        "会不爽，但尽量压住，先把事情处理好",
        "看打乱到什么程度",
        "会明显烦躁，也会直接说出来",
        "情绪会立刻写在脸上，现场气氛跟着变",
      ],
    },
    {
      id: "novice_c2",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "你代表小组参加积分赛，赛制允许你们选择更轻松的晋级路线，但这样会被人说“不够硬气”。你会：",
      options: [
        "当然选轻松路线，能让小组拿好成绩最重要",
        "规则允许就可以选，没必要主动给自己加难度",
        "看对手、赛制和大家想法",
        "可以理解，但我会更想堂堂正正打过去",
        "不选，宁愿难一点也要让成绩站得住",
      ],
    },
    {
      id: "novice_t2",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "你更喜欢哪种团队故事？",
      options: [
        "主角一个人逆天改命，全队都靠他翻盘",
        "天才人物在关键时刻站出来",
        "都能看",
        "一群人互相成就，把事一起做成",
        "没有绝对主角，每个人按分工把大事做成",
      ],
    },
    {
      id: "novice_r2",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "你面前有一个“成功就大赚、失败会亏不少”的选择。你更可能：",
      options: [
        "冲，失败也认，错过机会比亏损更难受",
        "回报足够高的话，可以试一把",
        "算完再说",
        "准备比较充分再动，不想裸赌",
        "不碰，高收益不值得把已有成果赔进去",
      ],
    },
    {
      id: "novice_e2",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "遇到特别开心的事，你更像：",
      options: [
        "马上发动态、发语音，让所有人一起热闹",
        "会明显表现出来，也愿意分享给别人",
        "看身边是谁",
        "会开心，但不一定表现得很夸张",
        "心里很爽，表面基本看不出来",
      ],
    },
    {
      id: "novice_c3",
      group: "标准测试",
      dim: "C",
      leftFirst: true,
      text: "小组比赛里，队友想用一些“拖节奏、干扰对面心态”的小动作来守住胜利。你更接近：",
      options: [
        "反对，靠这种方式赢我也觉得不舒服",
        "可以理解紧张，但别越过公平底线",
        "看动作尺度和比赛重要性",
        "适度干扰可以接受，关键时刻别太天真",
        "为了团队荣誉，规则边缘能用就用",
      ],
    },
    {
      id: "novice_t3",
      group: "标准测试",
      dim: "T",
      leftFirst: true,
      text: "做小组任务时，最让你安心的配置是：",
      options: [
        "所有人按同一套计划配合，没人脱离整体节奏",
        "有人愿意互相兜底、及时补位",
        "能完成就行",
        "有一个强人能在关键处拍板",
        "有个大腿负责把结果拉满，其他人跟上就行",
      ],
    },
    {
      id: "novice_r3",
      group: "标准测试",
      dim: "R",
      leftFirst: true,
      text: "如果两条路线都能到终点，你更喜欢：",
      options: [
        "慢一点也可以，成功率和安全感必须最高",
        "稳扎稳打，偶尔提速但别出大意外",
        "两种都能接受",
        "快一点，承担一些波动也能接受",
        "高风险高回报才有意思，越有冲击力越值得试",
      ],
    },
    {
      id: "novice_e3",
      group: "标准测试",
      dim: "E",
      leftFirst: true,
      text: "被别人误解，而且这件事你很在意时，你通常更像：",
      options: [
        "先不回应，把情绪完全压住，等事实说话",
        "会忍一忍，之后再私下解释",
        "看误解有多严重",
        "会马上表达不满，把态度亮出来",
        "必须当场说清楚，声音和气势都不能输",
      ],
    },
    {
      id: "novice_c4",
      group: "标准测试",
      dim: "C",
      leftFirst: false,
      text: "你支持的小队赢了冠军，但过程里用了不少规则边缘的策略，观感不算体面。你会：",
      options: [
        "冠军最重要，过程难看也是赢法的一部分",
        "会庆祝，过程瑕疵别太过分就行",
        "看那些策略到底到什么程度",
        "会庆祝但有点遗憾，希望下次赢得更漂亮",
        "如果过程不体面，这个冠军我很难真正认可",
      ],
    },
    {
      id: "novice_t4",
      group: "标准测试",
      dim: "T",
      leftFirst: false,
      text: "在一个需要多人配合的挑战里，你更愿意成为哪种人？",
      options: [
        "所有人都等我出手，我来决定成败",
        "能在关键时刻一锤定音的人",
        "都可以",
        "让团队运转更顺的人",
        "宁愿做把所有人连起来的稳定连接点",
      ],
    },
    {
      id: "novice_r4",
      group: "标准测试",
      dim: "R",
      leftFirst: false,
      text: "临场突然出现一个大胆新方案，成功收益很高，但没有充分演练。你会：",
      options: [
        "立刻试，机会错过不再有，失败也认",
        "直觉和收益都不错的话就上",
        "先听两边理由",
        "准备不足就先按原计划，别乱动",
        "关键时候绝不实验，稳定执行比惊喜重要",
      ],
    },
    {
      id: "novice_e4",
      group: "标准测试",
      dim: "E",
      leftFirst: false,
      text: "朋友聚会进入最热闹的阶段时，你更常处于：",
      options: [
        "人群中心，负责把场子彻底点起来",
        "熟起来话很多，情绪来得也快",
        "看熟不熟",
        "比较克制，熟人面前才慢慢打开",
        "安静观察，能不抢话就不抢话",
      ],
    },
  ];

  const results = [
    { key: "规则坚守×团队至上", label: "隐身者", player: "梅西", extreme: "梅西 隐身梅" },
    { key: "规则坚守×个人英雄", label: "绅士", player: "莫德里奇" },
    { key: "荣誉至上×团队至上", label: "红牌英雄", player: "巴尔韦德" },
    { key: "荣誉至上×个人英雄", label: "独裁者", player: "姆巴佩", extreme: "c罗 数据罗" },
    { key: "规则坚守×保守求稳", label: "老实人", player: "坎特", extreme: "梅西 隐身梅" },
    { key: "规则坚守×冒险激进", label: "骑士", player: "贝林厄姆" },
    { key: "荣誉至上×保守求稳", label: "卧草者", player: "大马丁" },
    { key: "荣誉至上×冒险激进", label: "跳水者", player: "C罗", extreme: "c罗 跳水罗" },
    { key: "规则坚守×冷静隐忍", label: "小鹿斑比", player: "穆西亚拉", extreme: "梅西 受气梅" },
    { key: "规则坚守×张扬外放", label: "魔人布欧", player: "哈兰德" },
    { key: "荣誉至上×冷静隐忍", label: "黄牌大师", player: "卡塞米罗" },
    { key: "荣誉至上×张扬外放", label: "挑衅者", player: "维尼修斯", extreme: "c罗 詹姆斯" },
    { key: "团队至上×保守求稳", label: "回传者", player: "赖斯", extreme: "梅西 詹姆斯" },
    { key: "团队至上×冒险激进", label: "抽奖者", player: "维尔茨" },
    { key: "个人英雄×保守求稳", label: "吃饼者", player: "哈兰德" },
    { key: "个人英雄×冒险激进", label: "舞者", player: "内马尔", extreme: "c罗 浪射罗" },
    { key: "团队至上×冷静隐忍", label: "“我的”人", player: "哈利凯恩", extreme: "梅西 散步梅" },
    { key: "团队至上×张扬外放", label: "保镖", player: "德保罗" },
    { key: "个人英雄×冷静隐忍", label: "亚洲式球王", player: "孙兴慜" },
    { key: "个人英雄×张扬外放", label: "皇毛", player: "亚马尔", extreme: "c罗 摊手罗" },
    { key: "保守求稳×冷静隐忍", label: "苟分者", player: "罗德里", extreme: "梅西 散步梅" },
    { key: "保守求稳×张扬外放", label: "场上教练", player: "基米希" },
    { key: "冒险激进×冷静隐忍", label: "带派者", player: "奥利赛" },
    { key: "冒险激进×张扬外放", label: "摊手者", player: "B费", extreme: "c罗 越位罗" },
  ];

  const hiddenResults = {
    game: {
      label: "游戏王",
      player: "登贝莱",
      kind: "隐藏人格",
      reason: "你不仅选择了游戏，还在二次确认中表现出极高痴迷度，系统正式把你送进游戏分支。",
    },
    cat: {
      label: "哈基米",
      player: "阿什拉夫",
      kind: "隐藏人格",
      reason: "你不仅选择了猫猫，还在二次确认中表现出极高痴迷度，系统判定你的精神边后卫已经转入猫科。",
    },
    troll: {
      label: "串子",
      player: "",
      kind: "隐藏人格",
      reason: "你在开场分流里主动暴露反串倾向，正常人格库只能先退后一步。",
    },
    fun: {
      label: "乐子人",
      player: "",
      kind: "隐藏人格",
      reason: "你对梅罗之争的投入主要来自围观与吃瓜，系统把你归入看台娱乐部门。",
    },
    balanced: {
      label: "勤笑公",
      player: "莱奥",
      kind: "隐藏人格",
      reason: "你的四个维度强度完全相同，系统判定你达成了罕见的全维度均衡。",
    },
  };

  return {
    dimensions,
    dimensionOrder: dimensions.map((dimension) => dimension.key),
    introQuestions,
    answerModeQuestion,
    hiddenQuestion,
    hiddenConfirmationQuestions,
    questionBanks: {
      fan: fanQuestions,
      novice: noviceQuestions,
    },
    results,
    hiddenResults,
  };
})();
